// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Backend.Models;

public partial class DetallesTurno
{
    public int IdDetalle { get; set; }

    public int IdServicio { get; set; }

    public int IdTurno { get; set; }

    public string Observaciones { get; set; }
    [JsonIgnore]
    public virtual Servicio IdServicioNavigation { get; set; }
    [JsonIgnore]
    public virtual Turno IdTurnoNavigation { get; set; }
}