// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Backend.Models;

public partial class Servicio
{
    public int IdServicio { get; set; }

    public string Nombre { get; set; }

    public decimal Costo { get; set; }

    public bool EnPromocion { get; set; }
    [JsonIgnore]
    public virtual ICollection<DetallesTurno> DetallesTurnos { get; set; } = new List<DetallesTurno>();
}