// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Actividad08Back.Models;

public partial class Turno
{
    public int IdTurno { get; set; }

    public DateOnly Fecha { get; set; }

    public TimeOnly Hora { get; set; }

    public int IdCliente { get; set; }

    public int IdServicio { get; set; }
    [JsonIgnore]
    public virtual Cliente IdClienteNavigation { get; set; }
    [JsonIgnore]
    public virtual Servicio IdServicioNavigation { get; set; }
}